# Generated by Django 3.0.6 on 2020-05-30 09:52

from django.db import migrations
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200523_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchingwords',
            name='weight',
            field=myapp.models.IntegerRangeField(default=5),
            preserve_default=False,
        ),
    ]
