# Generated by Django 3.0.6 on 2020-05-31 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_matchingwords_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='GroupWords',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='groupword',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='matchingwords',
            old_name='groupwords',
            new_name='category',
        ),
    ]
