# Generated by Django 3.0.6 on 2020-05-31 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200530_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchingwords',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.SubCategory'),
            preserve_default=False,
        ),
    ]
